title: What's Good?
email: team@sdee.co
description: > # this means to ignore newlines until "baseurl:"
  Welcome to What's Good? Let's share and learn what's good in our everyday life. Be inspired. Be alive.
permalink: ':title/'
baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: What's Good? # add your name
author-pic: reallife.jpg
about-author: เรื่องดีมีอยู่ในทุกที่ทุกเวลา ในทุกๆ วัน เรายิ้มให้กัน พวกเราแบ่งปันเรื่องดีๆ แม้ในสิ่งเล็กๆ น้อยๆ ความดีและความงามพร้อมจะนำความสุขและสดชื่นมาให้แก่พวกเราเสมอ ขอความดีจงเบ่งบานทั่วทั้งจักรวาลนี้ด้วยเทอญ

# Contact links
email: team@sdee.co # Add your Email address
phone: (+66)02 939 0491 # Add your Phone number
website: www.sdee.co # Add your website, do not add http://
linkedin: udomsak-agsornwong-1a735a31 # Add your Linkedin handle
github: sdeesreallife # Add your Github handle
twitter: '@odd_daboss' # Add your Twitter handle
facebook: SolutionDee # Add your Facebook handle
instagram: sdees.reallife # Add your Instagram handle
pinterest: odddaboss # Add your Pinterest handle

# Newsletter
mailchimp: sdee.us17.list-manage.com/subscribe/post?u=bc3147fd274300311454d00a4&amp;id=3ce19f9fc9 # Add your MailChimp form identifier.

# Disqus
discus_identifier: whatsgood-1 # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
